### ISSUE TITLE
Question about formula.smt2

### ISSUE THREAD

**Issue by sequencer** [RafaelTupynamba/SMTSampler#3]
Thank you for this great work!
I notice this repository didn't provide a `formula.smt2` presented in readme
If I wanna generate random x y in such constraints:
```smt
(set-info :status unknown)
(set-logic QF_LIA)
(declare-fun max () Int)
(declare-fun min () Int)
(declare-fun typ () Int)
(assert
 (let (($x21 (>= max 64)))
 (let (($x10 (= min 16)))
 (let (($x20 (and (< typ max) (> typ min) (< max 128))))
 (and $x20 $x10 $x21)))))
(check-sat)
(get-model)
 ```
What `formula.smt2` is supposed to be?
I tried this file but it failed in 
https://github.com/RafaelTupynamba/SMTSampler/blob/master/smtsampler.cpp#L226
I think my smt2 file is not correct for this usage.

**Comment by sequencer** [comment]
success adding `(get-model)`.

**Comment by RafaelTupynamba** [comment]
The supported logic is QF_AUFBV.
Can you encode your problem using bit-vectors instead of infinite precision integers?
