### ISSUE TITLE
Query while running the file

### ISSUE THREAD

**Issue by nalinish** [RafaelTupynamba/SMTSampler#4]
Hello, 

Whenever I am running the file, 
it is showing that could not read the input format.$ ./smtsampler -6 1000000 -10 3600.0 --smtbv  formula.smt2.samples
null
Could not read input formula.
it is saying that the ast is null.
How do I have to give input to the file.

**Comment by RafaelTupynamba** [comment]
You need to give an input file in `.smt2` format.
Your command seems to be specifying `formula.smt2.samples` as input. This would be wrong: the `.smt2.samples` file will be the output of the algorithm.
